Repository Escalar-Alcoia-i-Comtat/App, pull requests merged in 2025-05, with the labels that each got.

#392 Got rid of deprecated cache storages in favor of Coil
  .run/Desktop.run.xml
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/cache/CacheContainer.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/cache/ImageStorage.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
Labels: feature

#395 Added credits to CEA
  composeApp/src/commonMain/composeResources/drawable/cea.xml
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/AppRoot.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/model/SettingsModel.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/pages/SettingsPage.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/AppScreen.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/IntroScreen.kt
Labels: feature

#397 Fix file change not being marked as dirty on the editor
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/model/EditorModel.kt
Labels: feature

#398 Fixed patch when only a file is selected
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/exception/StringException.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/network/AdminBackend.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/model/EditorModel.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/EditorScreen.kt
Labels: bug

#399 Disabled progress display for Android's InApp updates
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/android/MainActivity.kt
  composeApp/src/androidMain/res/values-ca/strings.xml
  composeApp/src/androidMain/res/values-es/strings.xml
  composeApp/src/androidMain/res/values/strings.xml
Labels: feature

#400 Added 3+ and 4+ degrees
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/generic/Grade.kt
Labels: feature

#401 Increased item padding to differentiate items
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/DataList.kt
Labels: gui

#402 Added full screen map view
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/app/ui/platform/MapComposable.android.kt
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/AppRoot.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/navigation/Destinations.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/platform/MapComposable.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/DataList.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/MapScreen.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/SectorsScreen.kt
  composeApp/src/desktopMain/kotlin/org/escalaralcoiaicomtat/app/ui/platform/MapComposable.desktop.kt
  composeApp/src/iosMain/kotlin/ui/platform/MapComposable.ios.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/ui/platform/MapComposable.wasmJs.kt
Labels: feature

#404 Use WorkManager for sync on Android
  composeApp/build.gradle.kts
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/android/MainActivity.kt
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/android/SyncWorker.kt
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/app/sync/SyncManager.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/AppRoot.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/sync/DataSync.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/sync/SyncManager.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/pages/SettingsPage.kt
  composeApp/src/desktopMain/kotlin/org/escalaralcoiaicomtat/app/sync/SyncManager.kt
  composeApp/src/mobileMain/kotlin/push/PushNotifications.kt
  gradle/libs.versions.toml
Labels: android

#405 Add crash reports initialization in Android
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/android/MainActivity.kt
Labels: android, feature

#406 Fix edit button showing on path dialog
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
Labels: bug

#408 Fix sketch id editing
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/EditorScreen.kt
Labels: bug

#410 Translations update from Weblate
  composeApp/src/commonMain/composeResources/values-ca/strings.xml
  composeApp/src/commonMain/composeResources/values-es/strings.xml
Labels: gui

#409 Allow image formats other than PNG
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/model/EditorModel.kt
Labels: refactoring

#412 Enabled tracing in Android for Sentry
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/app/Sentry.android.kt
Labels: android

#415 Fixed KMZ decoding on iOS
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/cache/ZipFile.kt
  composeApp/src/iosMain/kotlin/org/escalaralcoiaicomtat/app/platform/ZipFileHandler.kt
Labels: ios

#414 Added support for path blocks
  .run/Browser.run.xml
  composeApp/schemas/org.escalaralcoiaicomtat.app.database.AppDatabase/3.json
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/android/App.kt
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/android/BlockingSyncWorker.kt
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/android/DataSyncWorker.kt
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/android/MainActivity.kt
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/android/SyncWorker.kt
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/app/sync/SyncManager.kt
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/AppRoot.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/Area.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/Blocking.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/DataType.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/Entity.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/Path.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/Sector.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/Zone.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/generic/BlockingRecurrenceYearly.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/generic/BlockingTypes.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/database/DataTypeInterface.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/database/DatabaseInterface.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/database/EntityInterface.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/database/Settings.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/network/BasicBackend.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/network/response/data/BlockListResponse.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/sync/BlockingSync.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/sync/DataSync.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/sync/SyncManager.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/sync/SyncProcess.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/model/SettingsModel.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/pages/SettingsPage.kt
  composeApp/src/desktopMain/kotlin/org/escalaralcoiaicomtat/app/main.kt
  composeApp/src/desktopMain/kotlin/org/escalaralcoiaicomtat/app/sync/SyncManager.kt
  composeApp/src/iosMain/kotlin/org/escalaralcoiaicomtat/app/Initialization.ios.kt
  composeApp/src/iosMain/kotlin/org/escalaralcoiaicomtat/app/sync/SyncManager.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/AppDatabase.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/Converters.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/DatabaseInterface.platform.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/AreasDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/BaseDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/BlockingDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/DataTypeDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/PathsDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/SectorsDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/ZonesDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/entity/BlockingEntity.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/entity/DatabaseEntity.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/database/Database.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/database/DatabaseDataTypeInterface.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/database/DatabaseEntityInterface.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/database/DatabaseInterface.wasmJs.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/database/Interfaces.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/main.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/sync/SyncManager.kt
Labels: feature

#419 Added display of path blocks
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/Blocking.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/generic/BlockingRecurrenceYearly.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/generic/BlockingTypes.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/database/BlockingInterface.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/database/DatabaseInterface.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/list/PathListItem.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/model/DataScreenModel.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/model/PathsScreenModel.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
  composeApp/src/commonTest/kotlin/data/generic/TestBlockingRecurrenceYearly.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/DatabaseInterface.platform.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/BlockingDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/entity/BlockingEntity.kt
Labels: gui, feature

#423 Fix WASM implementation
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/database/DatabaseBlockingInterface.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/database/DatabaseInterface.wasmJs.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/database/Interfaces.kt
Labels: bug

#424 Add push notifications for blocking updates
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/android/push/PushMessagingService.kt
Labels: feature

#425 Added server stats display
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/database/EntityInterface.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/model/SettingsModel.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/pages/SettingsPage.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/AreasDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/BaseDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/BlockingDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/PathsDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/SectorsDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/ZonesDao.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/database/Database.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/database/DatabaseEntityInterface.kt
Labels: feature

#426 Changed grade storage to use `GradeValue`
  composeApp/schemas/org.escalaralcoiaicomtat.app.database.AppDatabase/4.json
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/DataTypes.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/Path.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/editable/EditablePitchInfo.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/generic/PitchInfo.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/serialization/GradeSerializer.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/network/AdminBackend.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/network/response/data/PathData.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/AppDatabase.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/Converters.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/PathsDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/entity/PathEntity.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/migrations/Migration3To4.kt
Labels: refactoring

#427 Improved pitch editor
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/generic/EndingInclination.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/generic/EndingInfo.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/form/FormListCreator.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/EditorScreen.kt
Labels: feature

#429 Added pitches display
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/EditorScreen.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
Labels: feature

#430 Fixed predictive back animations on Android
  composeApp/src/androidMain/kotlin/org/escalaralcoiaicomtat/app/platform/BackHandler.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/platform/BackHandler.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/AppScreen.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/EditorScreen.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/IntroScreen.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/SectorsScreen.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/ZonesScreen.kt
  composeApp/src/desktopMain/kotlin/org/escalaralcoiaicomtat/app/main.kt
  composeApp/src/desktopMain/kotlin/org/escalaralcoiaicomtat/app/platform/BackHandler.kt
  composeApp/src/iosMain/kotlin/org/escalaralcoiaicomtat/app/Gestures.ios.kt
  composeApp/src/iosMain/kotlin/org/escalaralcoiaicomtat/app/platform/BackHandler.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/platform/BackHandler.wasmJs.kt
Labels: android

#431 Added shared transitions for element title
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/AppRoot.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/modifier/SharedElement.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/DataList.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/MainScreen.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/SectorsScreen.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/ZonesScreen.kt
Labels: gui

#432 Improved initial loading time
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/DataTypes.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/entity/AreaEntity.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/entity/SectorEntity.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/entity/ZoneEntity.kt
Labels: performance

#434 Do not show pitches when it's empty
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
Labels: bug

#439 Fixed description display
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
Labels: bug

#440 Fix point edit algorithm
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/EditorScreen.kt
Labels: bug

#441 Add markdown support for path description
  composeApp/build.gradle.kts
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
  gradle/libs.versions.toml
Labels: feature

#442 Improve title transitions
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/modifier/SharedElement.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/DataList.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
Labels: gui

#443 Added loose rocks warning
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/generic/BlockingTypes.kt
Labels: feature

#444 Navigate to root after delete
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/AppRoot.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/EditorScreen.kt
Labels: bug

#447 Upgrade Firebase BOM to 33.14.0
  gradle/libs.versions.toml
Labels: dependencies

#451 Added more artificial grades (including +) and A0-A5
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/generic/Grade.kt
Labels: feature

#452 Added support for artificial grades as general
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/generic/Grade.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/form/FormDropdown.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/form/FormOptionPicker.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/EditorScreen.kt
Labels: feature

#453 Upgrade Compose Rich Editor to `1.0.0-rc12`
  gradle/libs.versions.toml
Labels: dependencies

#455 Moved rich editor implementations to common
  composeApp/build.gradle.kts
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/editor/RichTextEditor.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/editor/RichTextStyleButton.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/editor/RichTextStyleRow.kt
  composeApp/src/iosMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/editor/RichTextEditor.kt
  composeApp/src/jvmMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/editor/RichTextEditor.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/editor/RichTextEditor.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/editor/RichTextStyleButton.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/editor/RichTextStyleRow.kt
Labels: refactoring

#459 Added vandalism blocking type
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/generic/BlockingTypes.kt
Labels: feature

#464 Differentiated grade and aid grade
  composeApp/schemas/org.escalaralcoiaicomtat.app.database.AppDatabase/5.json
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/Path.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/editable/EditablePitchInfo.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/generic/Grade.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/data/generic/PitchInfo.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/network/AdminBackend.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/network/response/data/PathData.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/list/PathListItem.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/form/FormDropdown.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/EditorScreen.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/AppDatabase.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/Database.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/dao/PathsDao.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/entity/PathEntity.kt
  composeApp/src/platformMain/kotlin/org/escalaralcoiaicomtat/app/database/migrations/Migration4To5.kt
Labels: feature

#465 Add sketch id display on the overlay
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
Labels: feature

#467 Use proper desktop context menu
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/list/DataCard.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/ContextMenu.kt
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
  composeApp/src/desktopMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/ContextMenu.desktop.kt
  composeApp/src/mobileMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/ContextMenu.mobile.kt
  composeApp/src/wasmJsMain/kotlin/org/escalaralcoiaicomtat/app/ui/reusable/ContextMenu.wasmJs.kt
Labels: desktop, feature

#468 Migrate to ZoomImage
  composeApp/build.gradle.kts
  composeApp/src/commonMain/kotlin/org/escalaralcoiaicomtat/app/ui/screen/PathsScreen.kt
  gradle/libs.versions.toml
Labels: refactoring
